name: Test AWS OIDC Connection

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::008971661427:role/cicd-abilytics-role
          aws-region: us-east-1

      - name: Test S3 Access
        run: aws s3 ls
